### ISSUE TITLE
App fails to update Obsidian Note with additional Highlights

### ISSUE THREAD

**Issue by davebhc71** [getmatterapp/obsidian-matter#49] opened 2023-01-25 13:21 UTC
The comment made by @Calorion (since Closed) is STILL happening. The sync issue has NOT been corrected and new highlights are NOT appended to the ‘original’ sync. So I would suggest revisiting this issue since NOW Matter is a subscription App that is NOT working as advertised with Obsidian.

**Comment by hunterclarke** [comment] 2023-01-25 13:30
Hi, I saw your previous comment and haven't had a chance to investigate fully. However, I'm unable to replicate the issue. If I add a highlight to an article that has already synced over, the highlight gets added to the bottom of the note.

I'm happy to work with you (and @Calorion) to figure out what's going on here. But I'm going to need some more details.

1. Are you still authenticated in the Matter plugin settings?
2. How are you triggering the sync when you expect new highlights to be added?
3. Is this occurring with highlights only, or notes on highlights, or both?

Thanks for the help.

**Comment by hunterclarke** [comment] 2023-01-25 13:35
Oh and last question: have you moved or renamed the file since the original sync?

**Comment by davebhc71** [comment] 2023-01-25 16:20
Hi Hunter- I’ll reply to these three 1st, then the subsequent email. First, let me say that, the app and plugin ARE amazing. I use them every day on my Apple iPad Air, latest M1 generation. And, I’ve already subscribed to the app. See below….On Jan 25, 2023, at 8:30 AM, Hunter Clarke ***@***.***> wrote:﻿
Hi, I saw your previous comment and haven't had a chance to investigate fully. However, I'm unable to replicate the issue. If I add a highlight to an article that has already synced over, the highlight gets added to the bottom of the note.
I'm happy to work with you (and @Calorion) to figure out what's going on here. But I'm going to need some more details.

Are you still authenticated in the Matter plugin settings?Yes. Sync otherwise works as far as I can tell. 
How are you triggering the sync when you expect new highlights to be added?I use the Command Palette command- “Matter-Sync”
Is this occurring with highlights only, or notes on highlights, or both?I’ve only been using the Highlights feature. Notes will come later.

Thanks for the help.

**Comment by davebhc71** [comment] 2023-01-25 16:33
﻿Hope you got the 1st reply- As to this question. No, but……In testing, I have deleted an ‘original’ sync note in order to see if the process will sync over the additional highlights. And the app/plugin works as expected. All subsequent highlights along with the originals Sync ‘over’ to Obsidian in the correct sequence.By the way, further info-1. All systems are up to date with their latest releases, Apple iPadOS (Beta 16.3) and Obsidian Insider- Mobile. Best regards.Dave BOn Jan 25, 2023, at 8:35 AM, Hunter Clarke ***@***.***> wrote:﻿
Oh and last question: have you moved or renamed the file since the original sync?

**Comment by hunterclarke** [comment] 2023-01-27 00:18
@davebhc71 I did some digging and I'm unable to see anything going wrong on my end. So I'm going to need a specific example to work with.

First, create a new highlight that doesn't sync over to Obsidian. Then you can email me (hunter at getmatter dot com) the details of the highlight:

1. Your Matter account email
2. The title of the article the highlight is in
3. The highlight text itself

Thanks! We'll get this sorted out.

**Comment by hunterclarke** [comment] 2023-02-21 21:00
This ended up not being a bug, but rather a misunderstanding of how sync works. The matter plugin appends highlights made after an initial sync to the bottom of the Obsidian note. We have to do that in order to preserve any edits that have been made to the note by the Obsidian user. Preventing data loss is more important than retaining the order of highlights given the trade-offs.

Based on that spec, the plugin is working as intended. I'm going to close this out.

I'd be happy to discuss further (or better yet, review any pull requests) if anyone finds a way around these constraints.

**Closed as completed by hunterclarke** 2023-02-21 21:00 UTC

**Comment by davebhc71** [comment] 2023-02-21 21:41
Yeh, I actually was wondering how to get around that issue once the highlights made it to a Note. The user could make edits/whatever to the Note which as you said would be lost. Win some lose some. Thanks for hearing me out. If there is a solution, I’m sure you folks will find it. Have a good rest of your day!On Feb 21, 2023, at 4:00 PM, Hunter Clarke ***@***.***> wrote:﻿
This ended up not being a bug, but rather a misunderstanding of how sync works. The matter plugin appends highlights made after an initial sync to the bottom of the Obsidian note. We have to do that in order to preserve any edits that have been made to the note by the Obsidian user. Preventing data loss is more important than retaining the order of highlights given the trade-offs.
Based on that spec, the plugin is working as intended. I'm going to close this out.
I'd be happy to discuss further (or better yet, review any pull requests) if anyone finds a way around these constraints.

**Comment by Calorion** [comment] 2023-03-03 23:19
>This ended up not being a bug, but rather a misunderstanding of how sync works. The matter plugin appends highlights made after an initial sync to the bottom of the Obsidian note.

That is precisely what you said would happen in [the original issue](https://github.com/getmatterapp/obsidian-matter/issues/42), and precisely what I said, there, was not happening. So I don’t understand what the misunderstanding is.

**Comment by hunterclarke** [comment] 2023-03-03 23:36
@Calorion if you read this report, it is strictly referring to the append to end functionality. That seems to be working fine. I'll address your other comment in the original issue.

**Comment by davebhc71** [comment] 2023-03-03 23:51
Hunter (Matter) commented-
“If I add a highlight to an article that has already synced over, the highlight gets added to the bottom of the note.”
I agree with that statement, Now. For whatever reason it wasn’t working that way when I 1st started using the plugin. After uninstalling, reinstalling and going thru the linking process with Obsidian a 2nd time Hunter’s comment above is accurate. While accurate, the subsequent sync described in the comment resulted in the addition highlight from the beginning of the article being appended to the very end of the note (hence…Apended). This kind of leaves the flow……disjointed, at minimum. So, my workaround, when making an additional highlight to an article, is to delete the original sync Note in Obsidian, make sure ‘Always Create Missing Files’ is turned on in Plugin settings and the subsequent sync will recreate the Note with the new/additional highlight in the proper place. For me, problem solved! YMMV.
