### ISSUE TITLE
Error message: "There was a problem syncing with Matter, try again later."

### ISSUE THREAD

**Issue by oliverholms** [getmatterapp/obsidian-matter#21] opened 2022-08-20 11:48 UTC
<img width="331" alt="Screenshot 2022-08-20 at 12 35 43@2x" src="https://user-images.githubusercontent.com/65342875/185744208-49a99a13-c98d-4440-b2f0-161bc0ea8226.png">

Hi,

I get the error message: "There was a problem syncing with Matter, try again later." when I try to manually sync with Matter from within Obsidian or when it auto-syncs. 

The Matter extension used to work for me (with the file duplications and other sync issues mentioned in another issue) when it was initially released. However, it stopped importing new notes and started to give the above alert, so I stopped using it. 

I just re-downloaded the extension and relinked it to see if I could get it to work and I am suffering from the same issue. 

I have the latest versions of both Obsidian (Version 0.15.9 (installer 0.15.8)) and Matter. I'm using an M1 MacBook Air, in case that is a factor. 

Do you have any insight into what is causing the issue?

Thank you.

**Comment by hunterclarke** [comment] 2022-10-11 16:38
@oliverholms I'm so sorry I missed this. Are you still experience the problem?

**Comment by oliverholms** [comment] 2022-10-12 01:42
I haven’t tried again in a while, but it was still an issue the last time I tried. Can you suggest a solution? Otherwise I was thinking of getting a Readwise subscription, connecting it to Matter and then using the Readwise plugin for Obsidian instead.

Oliver.

__________________________
OLIVER HOLMS
Director // Photographer
+447843 384146
www.oliverholms.com
IG: @oliverholms
Twitter: @OliverHolms

Art + Attention Newsletter
Sign up here for my newsletter about creative practice, curiosity and awareness.

**Comment by Barondane** [comment] 2022-10-19 21:24
Same exact error after the latest Obsidian update.

**Comment by hunterclarke** [comment] 2022-10-28 01:58
Thanks for digging on your end! I was combing logs earlier today looking for something related to authentication. I wouldn't have assumed it was a file naming error. I'll create a fix to truncate file names.

**Comment by chewycat** [comment] 2022-11-14 19:55
Hey @hunterclarke , I started getting this error yesterday or the day before.

I think it might've started after I changed the sync folder to be a folder-within-a-folder in Obsidian. Or possibly because the new subfolder had a period and space in its name? I tried deleting and re-installing the plugin, and changing it back to the original (top-level) folder location, but still getting the error. Any ideas?

Obsidian v1.0.3 (Installer 1.0.0)
Matter plugin v1.1.3

**Comment by hunterclarke** [comment] 2022-11-15 16:20
Thanks for the report @chewycat. Are you able to launch the debug console to see if there are any errors?

Mac shortcut: CMD+SHIFT+i
Windows shortcut: CTRL+SHIFT+i (I think)

**Comment by chewycat** [comment] 2022-11-15 18:48
Ah, the debug console showed that it was also caused by a nametoolong error— I had recently added [this podcast transcript](https://tim.blog/2022/11/12/chris-palmer-transcript/) to my Matter queue. I deleted it from Matter and no longer got the error.

Is there some way to get around this besides deleting the file?

**Comment by hunterclarke** [comment] 2022-11-18 17:44
I created a new issue for resolving that particular behavior https://github.com/getmatterapp/obsidian-matter/issues/43. You can follow over there.

**Closed by hunterclarke** 2022-11-18 17:44 UTC

**Comment by chewycat** [comment] 2022-11-18 19:36
Sounds good, thanks @hunterclarke !
